theme: jekyll-theme-slate
title: Machine Learning with R
footer: Kevin 
{% if kvinlazy %}
  <li>
    <a href="https://twitter.com/{{ site.twitter_username }}">
      <i class="fa fa-twitter"></i> Twitter
    </a>
  </li>
{% endif %}
